[App]
Name = "ai.h2o.wave.pptgenerator"
Version = "0.0.1"
Title = "PPT Generator"
Description = ""
Tags = ["GENERATIVE_AI", "OSS"]

[[Env]]
Name = "H2OGPTE_API_TOKEN"
SecretKey = "h2ogpte-key"

[[Env]]
Name = "H2OGPTE_URL"
SecretKey = "h2ogpte-url"
